In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('df_final.csv')

In [3]:
df.columns

Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment', 'Holiday',
       'Dept', 'Weekly_Sales', 'Type', 'Size', 'Year', 'Month_name', 'Month',
       'Quarter'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420285 entries, 0 to 420284
Data columns (total 20 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         420285 non-null  int64
 1   Date          420285 non-null  object
 2   Temperature   420285 non-null  float64
 3   Fuel_Price    420285 non-null  float64
 4   MarkDown1     420285 non-null  float64
 5   MarkDown2     420285 non-null  float64
 6   MarkDown3     420285 non-null  float64
 7   MarkDown4     420285 non-null  float64
 8   MarkDown5     420285 non-null  float64
 9   CPI           420285 non-null  float64
 10  Unemployment  420285 non-null  float64
 11  Holiday       420285 non-null  bool
 12  Dept          420285 non-null  int64
 13  Weekly_Sales  420285 non-null  float64
 14  Type          420285 non-null  object
 15  Size          420285 non-null  int64
 16  Year          420285 non-null  int64
 17  Month_name    420285 non-null  object
 18  Month         420285 non-null  int64
 19  Quarter       420285 non-null  int64
dtypes: bool(1), float64(10), int64(6), object(3)
memory usage: 61.3+ MB

In [5]:
#converting date
df['Date']=pd.to_datetime(df['Date'])

In [6]:
##Time features
df['Year']=df['Date'].dt.year
df['Month_name']=df['Date'].dt.month_name()
df['Month']=df['Date'].dt.month
df['Quarter']=df['Date'].dt.quarter

In [7]:
df.dtypes

Store                    int64
Date            datetime64[ns]
Temperature            float64
Fuel_Price             float64
MarkDown1              float64
MarkDown2              float64
MarkDown3              float64
MarkDown4              float64
MarkDown5              float64
CPI                    float64
Unemployment           float64
Holiday                   bool
Dept                     int64
Weekly_Sales           float64
Type                    object
Size                     int64
Year                     int32
Month_name              object
Month                    int32
Quarter                  int32
dtype: object

In [8]:
df.isna().sum()

Store           0
Date            0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Holiday         0
Dept            0
Weekly_Sales    0
Type            0
Size            0
Year            0
Month_name      0
Month           0
Quarter         0
dtype: int64

In [9]:
df.columns

Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment', 'Holiday',
       'Dept', 'Weekly_Sales', 'Type', 'Size', 'Year', 'Month_name', 'Month',
       'Quarter'],
      dtype='object')

In [10]:
## Holiday feature
df['Holiday'].unique()

array([False,  True])

In [11]:
df['Holiday']=df['Holiday'].astype(int)
df['Holiday'].unique()

array([0, 1])

In [12]:
## Promotion Features
df['Total_markdown']=(df['MarkDown1']+
                      df['MarkDown2']+
                      df['MarkDown3']+
                      df['MarkDown4']+
                      df['MarkDown5'])
df['Total_markdown'].head()

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: Total_markdown, dtype: float64

In [13]:
## Encoding Store type
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Type']=le.fit_transform(df['Type'])

In [14]:
df['Type'].unique()

array([0, 1, 2])

In [15]:
## Lag features
#Previous week
df=df.sort_values(['Date', 'Dept', 'Store'])
df['lag1']=df.groupby(['Dept', 'Store'])['Weekly_Sales'].shift(1)

In [16]:
#Previous 2 weeks
df['lag2']=df.groupby(['Dept', 'Store'])['Weekly_Sales'].shift(2)

In [17]:
df.columns

Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment', 'Holiday',
       'Dept', 'Weekly_Sales', 'Type', 'Size', 'Year', 'Month_name', 'Month',
       'Quarter', 'Total_markdown', 'lag1', 'lag2'],
      dtype='object')

In [18]:
df.isna().sum()

Store                0
Date                 0
Temperature          0
Fuel_Price           0
MarkDown1            0
MarkDown2            0
MarkDown3            0
MarkDown4            0
MarkDown5            0
CPI                  0
Unemployment         0
Holiday              0
Dept                 0
Weekly_Sales         0
Type                 0
Size                 0
Year                 0
Month_name           0
Month                0
Quarter              0
Total_markdown       0
lag1              3323
lag2              6606
dtype: int64

In [19]:
## Rolling average
df['Rolling_4_weeks']=(
    df.groupby(['Store','Dept'])['Weekly_Sales'].transform(lambda x:x.shift(1).rolling(4).mean()))

In [20]:
df['Rolling_4_weeks'].reset_index()

         index  Rolling_4_weeks
0            0              NaN
1        10229              NaN
2        20445              NaN
3        29472              NaN
4        39739              NaN
...        ...              ...
420280  410671        3875.1050
420281  420284         739.3750
420282   78530         130.0225
420283  313151         130.0525
420284  389889         291.2725

[420285 rows x 2 columns]

In [21]:
## dropping NaNs
df.dropna(inplace=True)

In [22]:
df.isna().sum()

Store              0
Date               0
Temperature        0
Fuel_Price         0
MarkDown1          0
MarkDown2          0
MarkDown3          0
MarkDown4          0
MarkDown5          0
CPI                0
Unemployment       0
Holiday            0
Dept               0
Weekly_Sales       0
Type               0
Size               0
Year               0
Month_name         0
Month              0
Quarter            0
Total_markdown     0
lag1               0
lag2               0
Rolling_4_weeks    0
dtype: int64

In [23]:
df.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,...,Type,Size,Year,Month_name,Month,Quarter,Total_markdown,lag1,lag2,Rolling_4_weeks
289,1,2010-03-05,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,...,0,151315,2010,March,3,1,0.0,19403.54,41595.55,32990.7700
10520,2,2010-03-05,47.17,2.625,0.0,0.0,0.0,0.0,0.0,211.006754,...,0,202307,2010,March,3,1,0.0,25962.32,58221.52,44925.4000
20702,3,2010-03-05,53.04,2.625,0.0,0.0,0.0,0.0,0.0,214.675139,...,1,37392,2010,March,3,1,0.0,4992.00,8918.31,8278.1525
29767,4,2010-03-05,43.49,2.654,0.0,0.0,0.0,0.0,0.0,126.578286,...,0,205863,2010,March,3,1,0.0,30107.54,49937.09,47160.3725
39996,5,2010-03-05,48.89,2.625,0.0,0.0,0.0,0.0,0.0,211.907165,...,1,34875,2010,March,3,1,0.0,7168.41,11417.67,11192.7675

In [24]:
df.dtypes

Store                       int64
Date               datetime64[ns]
Temperature               float64
Fuel_Price                float64
MarkDown1                 float64
MarkDown2                 float64
MarkDown3                 float64
MarkDown4                 float64
MarkDown5                 float64
CPI                       float64
Unemployment              float64
Holiday                     int64
Dept                        int64
Weekly_Sales              float64
Type                        int64
Size                        int64
Year                        int32
Month_name                 object
Month                       int32
Quarter                     int32
Total_markdown            float64
lag1                      float64
lag2                      float64
Rolling_4_weeks           float64
dtype: object

In [35]:
X = df.drop(['Weekly_Sales', 'Date', 'Month_name'], axis=1)
y = df['Weekly_Sales']

In [36]:
## splitting data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [39]:
df.to_csv('df_feature_eng.csv', index=False)